# https://taskfile.dev
version: '3'
tasks:

  default:
    desc: "List all tasks"
    cmds:
      - task -a

  # used by devbox
  run:
    desc: "Build the application"
    cmds:
      - go generate ./...
      - echo "http://localhost:3000"
      - go run ./cmd/*.go

  doc:
    desc: "Start godoc server"
    cmds:
      - echo http://localhost:6060 
      - godoc -http=:6060

  # used by devbox
  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  # used by devbox
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean
